version: '3.9'
services:
  mysql_400:
    container_name: mysql_400
    hostname: mysql_400
    image: mysql:8
    restart: always
    command:
      - --authentication-policy=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_force_recovery=0
    volumes:
      - ./mysql_400:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: base_de_dados
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
<<<<<<< HEAD
      TZ: America/Sao_Paulo
=======
      TZ: America/Sao_Paulo
>>>>>>> 7cc3e4e369f7b57dc37ac1d43d3bcb5350371964
